/*-------------------------------------------------------------------------
 *
 * regex_tokens.c -- hand-written mode-sensitive regex tokenizer
 *
 * Imported from pg_tre e03d6a8 (MIT, same author) and renamed into the
 * weave namespace.  See doc/specs/IMPORT_pg_tre.md for the mapping and
 * doc/CHANNELS.md for how this fits the fuzzy/regex channel.
 *
 * Copyright (c) 2025-2026, Gregory Burd
 *
 *-------------------------------------------------------------------------
 */

/*
 * src/query/regex_tokens.c - hand-written regex tokenizer.
 *
 * Lime handles the grammar (LALR(1)); this file emits tokens the
 * grammar consumes.  Regex requires mode-sensitive lexing (inside
 * [...] a '-' is a range operator, outside it's a literal; inside
 * {~m} the contents are a count) so a mode-free generated tokenizer
 * is not a great fit -- hence the hand roll.
 *
 * Phase 3: ASCII-only support. Multi-byte UTF-8 sequences are handled
 * in Phase 3.5. For Phase 3, each "codepoint" is a single byte.
 */

#include "postgres.h"

#include "weave/regex_ast.h"
#include "weave/utf8.h"

#include <ctype.h>

/* Token IDs from regex_grammar.h (generated by Lime). */
#define TOK_PIPE          1
#define TOK_CONCAT        2
#define TOK_STAR          3
#define TOK_PLUS          4
#define TOK_QUESTION      5
#define TOK_LBRACE        6
#define TOK_APPROX        7
#define TOK_INT           8
#define TOK_RBRACE        9
#define TOK_COMMA         10
#define TOK_LPAREN        11
#define TOK_RPAREN        12
#define TOK_LITERAL       13
#define TOK_DOT           14
#define TOK_ANCHOR_START  15
#define TOK_ANCHOR_END    16
#define TOK_LBRACKET      17
#define TOK_RBRACKET      18
#define TOK_CARET         19
#define TOK_DASH          20

typedef enum TokenizerMode
{
	MODE_NORMAL,
	MODE_BRACKET,      /* inside [...] */
	MODE_BRACE,        /* inside {m,n} or {~N} */
	MODE_BRACE_APPROX  /* inside {~N} after seeing ~ */
} TokenizerMode;

typedef struct TokenizerState
{
	const char *input;
	int         len;
	int         pos;
	TokenizerMode mode;
	int         bracket_depth;
	int         brace_depth;
	/*
	 * Byte offset of the first member position of the current bracket
	 * expression (just past '[', or past a leading '^' if the class is
	 * negated), or -1 when not inside one.  A '-' is a range operator only
	 * when it sits BETWEEN two members; POSIX makes it a literal when it is
	 * the first or last member instead, so `[-_]`, `[abc-]` and `[-]` all
	 * denote a literal dash.  Without this, the tokenizer has no way to
	 * tell "first member" from "range operator" and must guess -- see the
	 * '-' case in weave_tokenize_next() for the guess it used to make.
	 */
	int         bracket_first;
} TokenizerState;

/*
 * Initialize tokenizer state.
 */
static void
init_tokenizer(TokenizerState *ts, const char *input, int len)
{
	ts->input = input;
	ts->len = len;
	ts->pos = 0;
	ts->mode = MODE_NORMAL;
	ts->bracket_depth = 0;
	ts->brace_depth = 0;
	ts->bracket_first = -1;
}

/*
 * Peek at the next character without consuming it.
 */
static int
peek_char(TokenizerState *ts)
{
	PgWeaveCpStream s;
	if (ts->pos >= ts->len)
		return -1;
	pg_weave_cpstream_init(&s, ts->input + ts->pos, ts->len - ts->pos);
	return pg_weave_cpstream_next(&s);   /* decode, don't advance ts->pos */
}

/*
 * Consume and return the next codepoint (UTF-8 aware).
 *
 * Phase 3.5: decode codepoints, not raw bytes, so a multi-byte UTF-8
 * character produces a single LITERAL token whose `cp` matches the
 * codepoints emitted by ambuild's cpstream tokenizer.
 */
static int
next_char(TokenizerState *ts)
{
	PgWeaveCpStream s;
	int cp;
	if (ts->pos >= ts->len)
		return -1;
	pg_weave_cpstream_init(&s, ts->input + ts->pos, ts->len - ts->pos);
	cp = pg_weave_cpstream_next(&s);
	if (cp >= 0)
		ts->pos += s.src_pos;
	return cp;
}

/*
 * Parse an escape sequence starting after the backslash.
 * Returns the escaped codepoint or -1 on error.
 */
static int
parse_escape(TokenizerState *ts, WeaveParseCtx *ctx)
{
	int c = next_char(ts);

	switch (c)
	{
		case 'n': return '\n';
		case 't': return '\t';
		case 'r': return '\r';
		case '\\': return '\\';
		case '.': return '.';
		case '[': return '[';
		case ']': return ']';
		case '(': return '(';
		case ')': return ')';
		case '{': return '{';
		case '}': return '}';
		case '|': return '|';
		case '*': return '*';
		case '+': return '+';
		case '?': return '?';
		case '^': return '^';
		case '$': return '$';
		case '-': return '-';

		/* ASCII character classes (Phase 3: simple version) */
		case 'd': /* \d => [0-9] but for Phase 3 we return a special literal */
		case 'w': /* \w => [a-zA-Z0-9_] */
		case 's': /* \s => [ \t\n\r] */
			ctx->syntax_error = true;
			snprintf(ctx->errmsg, sizeof(ctx->errmsg),
					 "\\%c escapes not yet implemented in Phase 3", (char) c);
			return -1;

		case -1:
			ctx->syntax_error = true;
			snprintf(ctx->errmsg, sizeof(ctx->errmsg),
					 "unexpected end of pattern after backslash");
			return -1;

		default:
			/* Unknown escape; treat as literal */
			return c;
	}
}

/*
 * Parse a decimal integer starting at current position.
 * Returns the integer value and advances ts->pos.
 */
static int
parse_integer(TokenizerState *ts, WeaveParseCtx *ctx)
{
	int val = 0;
	int c;
	bool got_digit = false;

	while ((c = peek_char(ts)) != -1 && isdigit(c))
	{
		next_char(ts);
		val = val * 10 + (c - '0');
		got_digit = true;
	}

	if (!got_digit)
	{
		ctx->syntax_error = true;
		snprintf(ctx->errmsg, sizeof(ctx->errmsg),
				 "expected digit in repetition count");
		return -1;
	}

	return val;
}

/*
 * Main tokenization function.
 * Returns the token kind (> 0) or 0 on EOF, or -1 on error.
 */
int
weave_tokenize_next(WeaveParseCtx *ctx, WeaveToken *out)
{
	TokenizerState *ts;
	int c;

	/* Initialize tokenizer state on first call */
	if (ctx->tokenizer_state == NULL)
	{
		ts = (TokenizerState *) palloc0(sizeof(TokenizerState));
		init_tokenizer(ts, ctx->input, ctx->input_len);
		ctx->tokenizer_state = ts;
	}
	else
	{
		ts = (TokenizerState *) ctx->tokenizer_state;
	}

	/* EOF */
	if (ts->pos >= ts->len)
		return 0;

	c = next_char(ts);

	/* Handle mode-specific tokens */
	if (ts->mode == MODE_BRACKET)
	{
		/* Inside [...] */
		if (c == ']')
		{
			ts->bracket_depth--;
			if (ts->bracket_depth == 0)
				ts->mode = MODE_NORMAL;
			return TOK_RBRACKET;
		}
		else if (c == '-')
		{
			/*
			 * Only a '-' strictly between two other members is a range
			 * operator.  ts->pos already points past this '-' (next_char()
			 * consumed it above), so "first" means it sits right at
			 * bracket_first and "last" means the very next byte closes the
			 * expression.
			 */
			bool at_first = (ts->bracket_first >= 0 &&
							  ts->pos - 1 == ts->bracket_first);
			bool at_last = (ts->pos < ts->len &&
							 ts->input[ts->pos] == ']');

			if (at_first || at_last)
			{
				out->cp = '-';
				return TOK_LITERAL;
			}
			return TOK_DASH;
		}
		else if (c == '^')
		{
			/* ^ is CARET only at the start of the bracket expression */
			/* We'll let the parser handle the context */
			/*
			 * A negating '^' is itself the first byte of the bracket
			 * expression; POSIX still treats the byte after it as "first"
			 * (e.g. '-' in `[^-x]` is a literal), so shift bracket_first
			 * past the caret rather than leaving it pointed at the caret.
			 */
			if (ts->bracket_first >= 0 && ts->pos - 1 == ts->bracket_first)
				ts->bracket_first = ts->pos;
			return TOK_CARET;
		}
		else if (c == '\\')
		{
			int esc = parse_escape(ts, ctx);
			if (esc < 0)
				return -1;
			out->cp = esc;
			return TOK_LITERAL;
		}
		else
		{
			out->cp = c;
			return TOK_LITERAL;
		}
	}
	else if (ts->mode == MODE_BRACE || ts->mode == MODE_BRACE_APPROX)
	{
		/* Inside {m,n} or {~N} */
		if (c == '}')
		{
			ts->brace_depth--;
			if (ts->brace_depth == 0)
				ts->mode = MODE_NORMAL;
			return TOK_RBRACE;
		}
		else if (c == ',')
		{
			return TOK_COMMA;
		}
		else if (c == '~' && ts->mode == MODE_BRACE)
		{
			ts->mode = MODE_BRACE_APPROX;
			/* Parse the integer that follows ~ */
			int k = parse_integer(ts, ctx);
			if (k < 0)
				return -1;
			out->i = k;
			return TOK_APPROX;
		}
		else if (isdigit(c))
		{
			/* Put the digit back and parse the full integer */
			ts->pos--;
			int val = parse_integer(ts, ctx);
			if (val < 0)
				return -1;
			out->i = val;
			return TOK_INT;
		}
		else
		{
			ctx->syntax_error = true;
			snprintf(ctx->errmsg, sizeof(ctx->errmsg),
					 "unexpected character '%c' inside {}", (char) c);
			return -1;
		}
	}

	/* Normal mode */
	switch (c)
	{
		case '|':
			return TOK_PIPE;

		case '*':
			return TOK_STAR;

		case '+':
			return TOK_PLUS;

		case '?':
			return TOK_QUESTION;

		case '(':
			return TOK_LPAREN;

		case ')':
			return TOK_RPAREN;

		case '.':
			return TOK_DOT;

		case '^':
			return TOK_ANCHOR_START;

		case '$':
			return TOK_ANCHOR_END;

		case '[':
			ts->bracket_depth++;
			ts->mode = MODE_BRACKET;
			ts->bracket_first = ts->pos; /* first member starts right here */
			return TOK_LBRACKET;

		case '{':
			ts->brace_depth++;
			ts->mode = MODE_BRACE;
			return TOK_LBRACE;

		case '\\':
			{
				int esc = parse_escape(ts, ctx);
				if (esc < 0)
					return -1;
				out->cp = esc;
				return TOK_LITERAL;
			}

		default:
			/* Regular literal character */
			out->cp = c;
			return TOK_LITERAL;
	}
}
