/*-------------------------------------------------------------------------
 *
 * regex_grammar.h -- token IDs generated by Lime from regex_grammar.y (generated file)
 *
 * Imported from pg_tre e03d6a8 (MIT, same author) and renamed into the
 * weave namespace.  See doc/specs/IMPORT_pg_tre.md for the mapping and
 * doc/CHANNELS.md for how this fits the fuzzy/regex channel.
 *
 * Copyright (c) 2025-2026, Gregory Burd
 *
 *-------------------------------------------------------------------------
 */

#define PIPE                             1
#define CONCAT                           2
#define STAR                             3
#define PLUS                             4
#define QUESTION                         5
#define LBRACE                           6
#define APPROX                           7
#define INT                              8
#define RBRACE                           9
#define COMMA                           10
#define LPAREN                          11
#define RPAREN                          12
#define LITERAL                         13
#define DOT                             14
#define ANCHOR_START                    15
#define ANCHOR_END                      16
#define LBRACKET                        17
#define RBRACKET                        18
#define CARET                           19
#define DASH                            20
